name: "Build and deploy"
on:
  push:
    branches: [prod, pre-prod]

jobs:

  test_SSH:
    environment: ${{github.ref_name}}
    if: github.ref == 'refs/heads/pre-prod'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: SSH connection test
        uses: appleboy/ssh-action@dce9d565de8d876c11d93fa4fe677c0285a66d78
        with:
          username: ${{ secrets.SSH_USER }}
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          script: echo "I am connected to the server"
          
  publish:
    name: Publish to retype branch

    runs-on: ubuntu-latest

    steps:
      - name: Check-out code
        uses: actions/checkout@v3
      - name: Build dist
        uses: retypeapp/action-build@latest
      - name: Update deployment branch
        uses: retypeapp/action-github-pages@latest
        with:
          branch: retype-${{github.ref_name}}
          update-branch: true

  deploy_SSH:
    needs: [publish, test_SSH]
    if: github.ref == 'refs/heads/pre-prod'
    environment: ${{github.ref_name}}
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@dce9d565de8d876c11d93fa4fe677c0285a66d78
        with:
          username: ${{ secrets.SSH_USER }}
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ secrets.REPO_PATH }}
            git checkout retype-${{github.ref_name}}
            echo "--- BRANCH ---"
            git branch
            echo "--------------"
            git pull
            echo "Repo has been updated"

  send-message:
    runs-on: ubuntu-latest
    needs: deploy_SSH
    if: github.ref == 'refs/heads/pre-prod'
    name: Message Tchap - pre-PROD
    steps:
    - name: Get date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Send message to test channel
      id: matrix-chat-message
      uses: fadenb/matrix-chat-message@v0.0.6
      with:
        homeserver: ${{ secrets.MATRIX_SERVER }}
        token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
        channel: ${{ secrets.MATRIX_ROOM_ID }}
        message: | 
          ## [${{ steps.date.outputs.date }} - BOT] ${{github.repository}}
          ✨ Repo: **${{github.repository}}** \
          ✨ Branch: **${{github.ref_name}}** \
          ✨ Workflow: **${{github.workflow}}** \

          | Déploiement     | Info |
          | --- | --- |
          | **Repo**     | ${{github.repository}} |
          | **Branch**   | ${{github.ref_name}} |
          | **Workflow** | ${{github.workflow}} |
  
  send-message-prod:
    runs-on: ubuntu-latest
    needs: publish
    if: github.ref == 'refs/heads/prod'
    name: Message Tchap - PROD
    steps:
    - name: Get date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Send message to test channel
      id: matrix-chat-message
      uses: fadenb/matrix-chat-message@v0.0.6
      with:
        homeserver: ${{ secrets.MATRIX_SERVER }}
        token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
        channel: ${{ secrets.MATRIX_ROOM_ID }}
        message: | 
          ## [${{ steps.date.outputs.date }} - BOT] ${{github.repository}}
          ✨ Repo: **${{github.repository}}** \
          ✨ Branch: **${{github.ref_name}}** \
          ✨ Workflow: **${{github.workflow}}** \

          | Déploiement     | Info |
          | --- | --- |
          | **Repo**     | ${{github.repository}} |
          | **Branch**   | ${{github.ref_name}} |
          | **Workflow** | ${{github.workflow}} |

